"""sync_clinerules.py — keep .clinerules/01-builder-agent-prompt.md in sync
with the canonical system-prompt KG node.

The KG node at docs/builder/concepts/builder-agent-system-prompt.md is the
single source of truth for the AgentLoom builder agent's system prompt
(consumed by agentloom.builder_agent at startup). Cline (Layer-3 host #3)
needs the same prompt body inside its `.clinerules/` directory. To prevent
drift between the two, this script generates `.clinerules/01-builder-agent-
prompt.md` from the KG node and refuses to leave them out of sync.

Modes:
  default (--write)  rewrite .clinerules/01-builder-agent-prompt.md from the
                     KG node. Idempotent. Used by maintainers after editing
                     the KG node.
  --check            compare and exit 0 if in sync, exit 1 with a unified
                     diff if drifted. Used by CI / Tier-A validator.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts.agent.kg_context import load_system_prompt  # noqa: E402

CLINERULES_PROMPT_FILE = REPO_ROOT / ".clinerules" / "01-builder-agent-prompt.md"

GENERATED_HEADER = """# 01 — Builder Agent System Prompt (canonical)

<!-- DO NOT HAND-EDIT THIS FILE.

This file is GENERATED by scripts/sync_clinerules.py from the canonical
KG node at docs/builder/concepts/builder-agent-system-prompt.md.

To change the prompt, edit the KG node and re-run:
    python scripts/sync_clinerules.py

The Tier-A validator
    scripts/validators/clinerules_must_match_system_prompt_kg_node.py
fails CI if these two files drift apart.
-->

"""


def _build_target_text() -> tuple[str, str]:
    """Return (full_text_to_write, prompt_version_sha)."""
    body, sha = load_system_prompt()
    full = GENERATED_HEADER + f"<!-- prompt_version: {sha} -->\n\n" + body + "\n"
    return full, sha


def write_mode() -> int:
    target, sha = _build_target_text()
    CLINERULES_PROMPT_FILE.parent.mkdir(parents=True, exist_ok=True)
    if CLINERULES_PROMPT_FILE.exists() and CLINERULES_PROMPT_FILE.read_text(encoding="utf-8") == target:
        print(f"[sync_clinerules] already in sync (prompt_version {sha}); no write.")
        return 0
    CLINERULES_PROMPT_FILE.write_text(target, encoding="utf-8")
    print(f"[sync_clinerules] wrote {CLINERULES_PROMPT_FILE.relative_to(REPO_ROOT)} (prompt_version {sha}).")
    return 0


def check_mode() -> int:
    target, sha = _build_target_text()
    if not CLINERULES_PROMPT_FILE.exists():
        print(f"[sync_clinerules] FAIL: {CLINERULES_PROMPT_FILE.relative_to(REPO_ROOT)} does not exist.")
        print("                  Run: python scripts/sync_clinerules.py")
        return 1
    actual = CLINERULES_PROMPT_FILE.read_text(encoding="utf-8")
    if actual == target:
        print(f"[sync_clinerules] OK: in sync (prompt_version {sha}).")
        return 0
    print(f"[sync_clinerules] FAIL: drift detected between KG node and .clinerules/.")
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True),
        target.splitlines(keepends=True),
        fromfile=str(CLINERULES_PROMPT_FILE.relative_to(REPO_ROOT)),
        tofile="docs/builder/concepts/builder-agent-system-prompt.md (BEGIN-PROMPT body)",
    )
    sys.stdout.writelines(diff)
    print("\n[sync_clinerules] To fix: python scripts/sync_clinerules.py")
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero on drift; do not write")
    args = parser.parse_args()
    return check_mode() if args.check else write_mode()


if __name__ == "__main__":
    raise SystemExit(main())
